coep/coep/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from app1 import views
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.Home,name="home"),
    path('admin_g/', views.admin_g, name='admin_g'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('fe_pdf_boys/', views.fe_pdf_boys, name='fe_pdf_boys'),
    path('se_pdf_boys/', views.se_pdf_boys, name='se_pdf_boys'),
    path('te_pdf_boys/', views.te_pdf_boys, name='te_pdf_boys'),
    path('be_pdf_boys/', views.be_pdf_boys, name='be_pdf_boys'),
    path('fe_pdf_girls/', views.fe_pdf_girls, name='fe_pdf_girls'),
    path('se_pdf_girls/', views.se_pdf_girls, name='se_pdf_girls'),
    path('te_pdf_girls/', views.te_pdf_girls, name='te_pdf_bgirls'),
    path('be_pdf_girls/', views.be_pdf_girls, name='be_pdf_girls'),
    path('fe_pdf_w_boys/', views.fe_pdf_w_boys, name='fe_pdf_w_boys'),
    path('se_pdf_w_boys/', views.se_pdf_w_boys, name='se_pdf_w_boys'),
    path('te_pdf_w_boys/', views.te_pdf_w_boys, name='te_pdf_w_boys'),
    path('be_pdf_w_boys/', views.be_pdf_w_boys, name='be_pdf_w_boys'),
    path('fe_pdf_w_girls/', views.fe_pdf_w_girls, name='fe_pdf_w_girls'),
    path('se_pdf_w_girls/', views.se_pdf_w_girls, name='se_pdf_w_girls'),
    path('te_pdf_w_girls/', views.te_pdf_w_girls, name='te_pdf_w_bgirls'),
    path('be_pdf_w_girls/', views.be_pdf_w_girls, name='be_pdf_w_girls'),
    path('fe_pdf_f_boys/', views.fe_pdf_f_boys, name='fe_pdf_f_boys'),
    path('se_pdf_f_boys/', views.se_pdf_f_boys, name='se_pdf_f_boys'),
    path('te_pdf_f_boys/', views.te_pdf_f_boys, name='te_pdf_f_boys'),
    path('be_pdf_f_boys/', views.be_pdf_f_boys, name='be_pdf_f_boys'),
    path('fe_pdf_f_girls/', views.fe_pdf_f_girls, name='fe_pdf_f_girls'),
    path('se_pdf_f_girls/', views.se_pdf_f_girls, name='se_pdf_f_girls'),
    path('te_pdf_f_girls/', views.te_pdf_f_girls, name='te_pdf_f_bgirls'),
    path('be_pdf_f_girls/', views.be_pdf_f_girls, name='be_pdf_f_girls'),
    path('fe_room_boys/',views.fe_room_boys,name='fe_room_boys'),
    path('fe_room_girls/',views.fe_room_girls,name='fe_room_girls'),
    path('se_room_boys/',views.se_room_boys,name='se_room_boys'),
    path('se_room_girls/',views.se_room_girls,name='se_room_girls'),
    path('te_room_boys/',views.te_room_boys,name='te_room_boys'),
    path('te_room_girls/',views.te_room_girls,name='te_room_girls'),
    path('be_room_boys/',views.be_room_boys,name='be_room_boys'),
    path('be_room_girls/',views.be_room_girls,name='be_room_girls'),
    path('profile/preference/',views.PreferenceClass.as_view(),name='preference'),
    path('profile/preference/',views.SearchAjaxSubmitView.as_view(),name='search-ajax-submit'),
    path('submitpreference/',views.prefer,name='save'),
    path('cancel/',views.cancellation,name='delete'),
    path('profile/',views.profile,name="profile"),
    path('profile/settings',views.ProSet,name="settings"),
    path('profile/transaction',views.transaction,name="transaction"),
    path('signup/', views.signup, name='signup'),
    path('edit/',views.edit,name="edit"),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',views.activate, name='activate'),
]



if settings.DEBUG :
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coep/app1/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()

class SignupForm(UserCreationForm):
    #email = forms.EmailField(max_length=200, help_text='Required')

    class Meta:
        model = User
        fields = ('username','password1', 'password2')



class admin_form(forms.Form):
    no_stud = forms.IntegerField()
    r_date = forms.DateTimeField()
    p_date = forms.DateTimeField()
    f_date = forms.DateTimeField()
    ra_date = forms.DateTimeField()
    pay_date = forms.DateTimeField()
    fields = ('no_stud','r_date','p_date','f_date','ra_date','pay_date')



class Preferenceform(forms.ModelForm):
    n1  = forms.CharField(max_length=40)
    n2  = forms.CharField(max_length=40)
    n3  = forms.CharField(max_length=40)

    class Meta:
        model  = User
        fields  = ('n1','n2','n3')

coep/templates/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,

http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

coep/templates/admin.html
<!DOCTYPE html>
<html>
<head>
	<title>Admin</title>
</head>
<body>
<form method="POST">
<!-- 	<label id='no_stud_id'>Enter the number of students per branch :- </label>
	<input id='no_stud_id' type="text" name="no_stud">
	<input type="submit" value="submit">
 -->
 	{% csrf_token %}
	<tr><th><label for="id_no_stud">No stud:</label></th><td><input type="number" name="no_stud" required id="id_no_stud" /></td></tr><br
<tr><th><label for="id_r_date">R date:</label></th><td><input type="date" name="r_date" required id="id_r_date" /></td></tr><br>
<tr><th><label for="id_p_date">P date:</label></th><td><input type="date" name="p_date" required id="id_p_date" /></td></tr><br>
<tr><th><label for="id_f_date">F date:</label></th><td><input type="date" name="f_date" required id="id_f_date" /></td></tr><br>
<tr><th><label for="id_ra_date">Ra date:</label></th><td><input type="date" name="ra_date" required id="id_ra_date" /></td></tr><br>
<tr><th><label for="id_pay_date">Pay date:</label></th><td><input type="date" name="pay_date" required id="id_pay_date" /></td></tr><br>
 	<input type="submit" value="submit">
 	<input type="submit" value="submit">
 </form>
</body>
</html>

coep/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login V1</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>
  {% block content %}
  {% endblock %}

<!--===============================================================================================-->
  <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
  <script src="{% static 'js/popper.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
  <script src="{% static 'js/select2.min.js' %}"></script>
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script >
    $('.js-tilt').tilt({
      scale: 1.1
    })
  </script>
<!--===============================================================================================-->
  <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

</body>

coep/templates/home.html
<!DOCTYPE html>
<html>
<head>
	<title>Home</title>
</head>
<body>
wellcom !!
</body>
</html>

coep/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Login V1</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
  <link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
<!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
<!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="{% static 'css/hamburgers.min.css' %}">
<!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="{% static 'css/select2.min.css' %}">
<!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>
  <div class="limiter">
    <div class="container-login100">
      <div class="wrap-login100">
        <div class="login100-pic js-tilt" data-tilt>
          <img src="{% static 'images/img-01.png' %}" alt="IMG">
        </div>
        <form class="login100-form validate-form">
          <span class="login100-form-title">
            Member Register
          </span>

        <form method="post">
          {% csrf_token %}
          <div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
            <input class="input100" type="text" name="username" placeholder="Email" required id="id_username" autocomplete="off">
            <span class="focus-input100"></span>
            <span class="symbol-input100">
              <i class="fa fa-envelope" aria-hidden="true"></i>
            </span>
          </div>
          <div class="wrap-input100 validate-input" data-validate = "Password is required">
            <input class="input100" type="password" name="password1" placeholder="Password" required id="id_password1" autocomplete="off">
            <span class="focus-input100"></span>
            <span class="symbol-input100">
              <i class="fa fa-lock" aria-hidden="true"></i>
            </span>
          </div>
          <div class="wrap-input100 validate-input" data-validate = "Password is required">
            <input class="input100" type="password" placeholder="Confirm Password" name="password2" required id="id_password2" autocomplete="off">
            <span class="focus-input100"></span>
            <span class="symbol-input100">
              <i class="fa fa-lock" aria-hidden="true"></i>
            </span>
          </div>
          <div class="container-login100-form-btn">
            <button class="login100-form-btn" type="submit">Register</button>
          </div>
        </form>

          <div class="text-center p-t-136">
              <span class="txt1">
                  Already have account?
                </span>
            <a class="txt2" href="signup/">
              Register
              <i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
            </a>
          </div>
        </form>
      </div>
    </div>
  </div>
<!--===============================================================================================-->
  <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
  <script src="{% static 'js/popper.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
  <script src="{% static 'js/select2.min.js' %}"></script>
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script >
    $('.js-tilt').tilt({
      scale: 1.1
    })
  </script>
<!--===============================================================================================-->
  <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

coep/templates/profile.html
<!doctype html>
<html>
  <head>

    <meta charset="utf-8">
    <title>Preference</title>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="https://intercoolerreleases-leaddynocom.netdna-ssl.com/intercooler-1.1.1.min.js"></script>
  </head>
  <body>

    {{err}}
    <form class="" method="post" action="{% url 'save' %}">
      {% csrf_token %}
      <p><label for="id_n1">N1:</label> <input type="text" name="n1" maxlength="40" required id="id_n1" list="cars"
        ic-post-to="{% url 'search-ajax-submit' %}"
        	       ic-trigger-on="keyup changed"
        	       ic-trigger-delay="300ms"
                 ic-target="#search-result-container"
                 
         /></p>
 <p><label for="id_n2">N2:</label> <input type="text" name="n2" maxlength="40" required id="id_n2" list="car2"
   ic-post-to="{% url 'search-ajax-submit' %}"
            ic-trigger-on="keyup changed"
            ic-trigger-delay="300ms"
            ic-target="#search-result-container"
    /></p>
 <p><label for="id_n3">N3:</label> <input type="text" name="n3" maxlength="40" required id="id_n3" list="car3"
   ic-post-to="{% url 'search-ajax-submit' %}"
            ic-trigger-on="keyup changed"
            ic-trigger-delay="300ms"
            ic-target="#search-result-container"
   /></p>
 <input type="submit" name="submit" value="submit">
        </form>
        <span id="search-result-container" style="display:none"></span>

        {% if query1 %}
        <datalist id="cars">
          {% for x in list1 %}
            <option> {{x.username}} | {{x.name}}</option>
          {% endfor %}
        </datalist>
        {% endif %}

        {% if query2 %}
        <datalist id="car2">
          {% for x in list2 %}
            <option>{{x.username}} | {{x.name}}</option>
          {% endfor %}
        </datalist>
        {% endif %}

        {% if query3 %}
        <datalist id="car3">
          {% for x in list3 %}
            <option> {{x.username}} | {{x.name}}</option>
          {% endfor %}
        </datalist>
        {% endif %}
        <div class="row page-titles">
            <div class="col-md-5 col-8 align-self-center">
                <h3 class="text-themecolor m-b-0 m-t-0">Settings</h3>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                    <li class="breadcrumb-item active">Settings</li>
                </ol>
            </div>
        </div>
  </body>
</html>

coep/templates/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login V1</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-pic js-tilt" data-tilt>
					<img src="{% static 'images/img-01.png' %}" alt="IMG">
				</div>
				<div class="login100-form validate-form">
					<!-- {% csrf_token %} -->
					<span class="login100-form-title">
						Student Register
						<span style="color:red;"> {{con}} </span>
					</span>
					

				<form method="POST" action="">
					{% csrf_token %}
					<div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
						<input class="input100" type="text" name="username" placeholder="College ID" required id="id_username" autocomplete="off">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-envelope" aria-hidden="true"></i>
						</span>
					</div>
					<div class="wrap-input100 validate-input" data-validate = "Password is required">
						<input class="input100" type="password" name="password1" placeholder="Password" required id="id_password1" autocomplete="off">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-lock" aria-hidden="true"></i>
						</span>
					</div>
					<div class="wrap-input100 validate-input" data-validate = "Password is required">
						<input class="input100" type="password" placeholder="Confirm Password" name="password2" required id="id_password2" autocomplete="off">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-lock" aria-hidden="true"></i>
						</span>
					</div>
					<div class="container-login100-form-btn">
						<button class="login100-form-btn" type="submit">Register</button>
					</div>
				</form>
				
					<div class="text-center p-t-45">
							<span class="txt1">
									Have an account?
								</span>
						<a class="txt2" href="/accounts/login">
							Log in
							<i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>
<!--===============================================================================================-->
	<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'js/popper.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'js/select2.min.js' %}"></script>
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<script >
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script>
<!--===============================================================================================-->
	<script src="{% static 'js/main.js' %}"></script>
</body>
</html>